const data=[
    {   
        id:"1",
        imgsrc:"logo192.png",
        title:"javaScript",
        text:"javascript frame work most popular  programing language in the earth its  programing language in the earth its",
        btn:"Read more",
        likes: 200, 
        views: 7500,
        comments: 30,
        category:"Documetary",      
    },{
        id:"2",
        imgsrc:"logo512.png",
        title:"React",
        text:"javascript frame work most popular  programing language in the earth its  programing language in the earth its ",
        btn:"Read more",
        likes: 200, 
        views: 7500,
        comments: 30,
        category:"Quotes",
    },{
        id:"3",
        imgsrc:"logo192.png",
        title:"Node.js",
        text:"javascript frame work most popular  programing language in the earth its  programing language in the earth its ",
        btn:"Read more",
        likes: 200,
        views: 7500,
        comments: 30,
        category:"Quotes",
    },{
        id:"4",
        imgsrc:"logo192.png",
        title:"Express.js",
        text:"javascript frame work most popular  programing language in the earth its  programing language in the earth its ",
        btn:"Read more",
        category:"Quotes",
    },{
        id:"5",
        imgsrc:"logo192.png",
        title:"next.js",
        text:"javascript frame work most popular  programing language in the earth its  programing language in the earth its ",
        btn:"Read more",
        category:"MorningEvolution",
    },{
        id:"6",
        imgsrc:"logo192.png",
        title:"Node.js",
        text:"javascript frame work most popular  programing language in the earth its  programing language in the earth its ",
        btn:"Read more",
        category:"MorningEvolution",
    },{
        id:"7",
        imgsrc:"logo512.png",
        title:"Node.js",
        text:"javascript frame work most popular  programing language in the earth its  programing language in the earth its ",
        btn:"Read more",
        category:"MorningEvolution", 
    },{
        id:"8",
        imgsrc:"logo512.png",
        title:"Node.js",
        text:"javascript frame work most popular  programing language in the earth its  programing language in the earth its ",
        btn:"Read more",
        category:"Documetary", 
    },{
        id:"9",
        imgsrc:"logo512.png",
        tittle:"Node.js",
        text:"javascript frame work most popular  programing language in the earth its  programing language in the earth its ",
        btn:"Read more",
        category:"Documetary", 
    },{
        id:"10",
        imgsrc:"logo512.png",
        title:"Node.js",
        text:"javascript frame work most popular  programing language in the earth its  programing language in the earth its ",
        btn:"Read more",
        category:"Documetary", 
    }

]
export default data;